//! This is a test sample that converts two OBJ files. It reads one, generates the convex hull of the geometry, and saves it as a new file.

use fxhash::FxHashMap;
use glam::Vec3;
use qhull_rayon::{TriangleIndices, generate_convex_hull};
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;
use tobj;
use tobj::LoadError;

/// Uses the tobj library to load the obj file, goes over all models in the obj file and collects the data.
fn load_vertices_from_file(path: &Path) -> Result<Vec<Vec3>, LoadError> {
    let data = tobj::load_obj(path, &tobj::OFFLINE_RENDERING_LOAD_OPTIONS);
    let mut result = Vec::new();

    let (models, _) = data?;
    for model in models.iter() {
        let mesh = &model.mesh;

        for v in 0..mesh.positions.len() / 3 {
            result.push(Vec3::new(
                mesh.positions[3 * v],
                mesh.positions[3 * v + 1],
                mesh.positions[3 * v + 2],
            ));
        }
    }

    Ok(result)
}

/// Flattens the data structure coming from the convex hull computation, removes all unnecessary vertices and does the +1 shift
/// needed for obj format.
fn flatten_vectors(
    vertices: &[Vec3],
    triangles: &[TriangleIndices],
) -> (Vec<Vec3>, Vec<TriangleIndices>) {
    let mut new_vertices = Vec::new();
    let mut new_triangles = Vec::new();

    let mut look_up = FxHashMap::<usize, usize>::default();
    for tri in triangles {
        let new_ind = tri
            .get_array()
            .into_iter()
            .map(|index| {
                *look_up.entry(index).or_insert_with(|| {
                    new_vertices.push(vertices[index]);
                    // We alreads take account of the +1 offset needed for obj
                    new_vertices.len()
                })
            })
            .collect::<Vec<_>>();
        new_triangles.push(TriangleIndices(new_ind[0], new_ind[1], new_ind[2]));
    }

    (new_vertices, new_triangles)
}

/// Generates an obj file from the data. Writes it out in simple ASCII format.
fn generate_target_file(
    out_path: &Path,
    vertices: &[Vec3],
    triangles: &[TriangleIndices],
) -> std::io::Result<()> {
    let mut out = BufWriter::new(File::create(out_path)?);

    writeln!(out, "# Generated by convex hull generator")?;
    writeln!(out, "o ConvexHull")?;
    for pos in vertices {
        writeln!(out, "v {:.6} {:.6} {:.6}", pos.x, pos.y, pos.z)?;
    }
    writeln!(out, "s 0")?;
    for tri in triangles {
        writeln!(out, "f {} {} {}", tri.0, tri.1, tri.2)?;
    }

    out.flush()?;
    Ok(())
}

/// Program that reads in an obj file and generates one for the convex hull.
fn main() {
    let commands = std::env::args().skip(1).collect::<Vec<String>>();
    if commands.len() < 2 {
        eprintln!("usage: command <in.obj> <out.obj>");
        return;
    }
    let in_file = Path::new(&commands[0]);
    let out_file = Path::new(&commands[1]);

    let vert_vec = match load_vertices_from_file(in_file) {
        Ok(vertices) => vertices,
        Err(e) => {
            eprintln!(
                "Failed to load raw data from file {} error {}",
                in_file.display(),
                e
            );
            return;
        }
    };

    let tri_vec = match generate_convex_hull(&vert_vec) {
        Ok(vec) => vec,
        Err(e) => {
            eprintln!("Failed to generate convex hull: {}", e);
            return;
        }
    };

    let (new_vertices, new_triangles) = flatten_vectors(&vert_vec, &tri_vec);

    if let Err(e) = generate_target_file(&out_file, &new_vertices, &new_triangles) {
        eprintln!(
            "Failed to generate target file {} error {}",
            out_file.display(),
            e
        );
    }
}
