//! This module contains a complete mesh; it is intended for the case that an indexing into the old
//! vertices is not sufficient, but a completely separate structure of vertices and triangle indices is wanted.
//! It rebuilds a new vertex array from existing data. It can be used with or independently of the
//! convex hull calculation.

use crate::TriangleIndices;
use fxhash::FxHashMap;
use glam::Vec3;
use std::fs::File;
use std::io::BufWriter;
use std::io::Write;
use std::path::Path;

/// The error that can happen in the construction of a mesh, if one of the indices handed over is not
/// in the vertex array.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IndexOutOfBoundsError(
    /// The index that is not contained in the vertices.
    pub usize
);

impl std::fmt::Display for IndexOutOfBoundsError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "Index out of bounds: {}", self.0)
    }
}

impl std::error::Error for IndexOutOfBoundsError {}

/// A complete mesh consisting of vertices with the position and the triangle indices.
/// When the mesh is constructed from the data of the convex hull generator, the
/// triangles are in counterclockwise  order seen from the outside.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Mesh {
    /// The vertex positions of the mesh.
    pub vertices: Vec<Vec3>,
    /// The mesh as single triangles.
    pub triangles: Vec<TriangleIndices>,
}

impl Mesh {
    /// Creates a mesh from the vertices and the triangles handed over. More vertices can be provided than are actually used.
    /// They will get compacted out during the process.
    ///
    /// # Error
    /// If one of the triangles contains an index that is not in the mesh, an error is returned.
    ///
    ///
    /// # Example
    /// ```
    /// # use std::error::Error;
    /// #
    /// # fn main() -> Result<(), Box<dyn Error>> {
    /// use glam::Vec3;
    /// use qhull_rayon::generate_convex_hull;
    /// use qhull_rayon::mesh::Mesh;
    /// let positions = [Vec3{x:0.0, y:0.0, z:0.0}, Vec3{x:1.0, y:0.0, z:0.0}, Vec3{x:0.0, y:1.0, z:0.0}, Vec3{x:0.0, y:0.0, z:1.0}, Vec3{x:0.1, y:0.1, z:0.1}];
    /// let indices = generate_convex_hull(&positions)?;
    /// let new_mesh = Mesh::new(&positions, &indices)?;
    /// assert_eq!(new_mesh.vertices.len(), 4, "We should have exactly four vertices left.");
    /// #
    /// #     Ok(())
    /// # }
    /// ```
    pub fn new(
        vertices: &[Vec3],
        triangles: &[TriangleIndices],
    ) -> Result<Mesh, IndexOutOfBoundsError> {
        // Validate the indices in advance
        if let Some(index) = triangles
            .iter()
            .flat_map(TriangleIndices::to_array)
            .find(|&index| index >= vertices.len())
        {
            return Err(IndexOutOfBoundsError(index));
        }

        let mut new_vertices = Vec::new();
        let mut new_triangles = Vec::new();

        let mut look_up = FxHashMap::<usize, usize>::default();
        for tri in triangles {
            let new_ind = tri.to_array().map(|index| {
                *look_up.entry(index).or_insert_with(|| {
                    new_vertices.push(vertices[index]);
                    new_vertices.len() - 1
                })
            });
            new_triangles.push(TriangleIndices::from_array(new_ind));
        }

        Ok(Mesh {
            vertices: new_vertices,
            triangles: new_triangles,
        })
    }

    /// Saves the current mesh as a simple Wavefront obj file. Plain positions and triangle indices
    /// are saved.
    ///
    /// # Error
    /// The io errors on file access.
    ///
    /// # Example
    ///
    /// ```no_run
    /// # use std::error::Error;
    /// #
    /// # fn main() -> Result<(), Box<dyn Error>> {
    /// use glam::Vec3;
    /// use qhull_rayon::generate_convex_hull;
    /// use qhull_rayon::mesh::Mesh;
    /// use std::path::Path;
    /// let positions = [Vec3{x:0.0, y:0.0, z:0.0}, Vec3{x:1.0, y:0.0, z:0.0}, Vec3{x:0.0, y:1.0, z:0.0}, Vec3{x:0.0, y:0.0, z:1.0}, Vec3{x:0.1, y:0.1, z:0.1}];
    /// let indices = generate_convex_hull(&positions)?;
    /// let new_mesh = Mesh::new(&positions, &indices)?;
    /// new_mesh.save_as_obj_file(Path::new("Processed.obj"))?;
    /// assert_eq!(new_mesh.vertices.len(), 4, "We should have exactly four vertices left.");
    /// #
    /// #     Ok(())
    /// # }
    /// ```
    pub fn save_as_obj_file(&self, path: &Path) -> std::io::Result<()> {
        let mut out = BufWriter::new(File::create(path)?);

        writeln!(out, "# Generated by convex hull generator")?;
        writeln!(out, "o ConvexHull")?;
        for pos in &self.vertices {
            writeln!(out, "v {:.6} {:.6} {:.6}", pos.x, pos.y, pos.z)?;
        }
        writeln!(out, "s 0")?;
        // The obj file is offset + 1
        for tri in &self.triangles {
            writeln!(out, "f {} {} {}", tri.0 + 1, tri.1 + 1, tri.2 + 1)?;
        }

        out.flush()?;
        Ok(())
    }
}
